---
- name: Deploy frontend application
  hosts: frontend_servers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create frontend HTML file
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Frontend Application</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
                  .container { max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                  h1 { color: #333; text-align: center; }
                  .form-group { margin-bottom: 20px; }
                  label { display: block; margin-bottom: 8px; font-weight: bold; color: #555; }
                  input[type="text"], input[type="email"] { width: 100%; padding: 12px; border: 2px solid #ddd; border-radius: 4px; font-size: 16px; box-sizing: border-box; }
                  input[type="text"]:focus, input[type="email"]:focus { border-color: #007bff; outline: none; }
                  button { background-color: #007bff; color: white; padding: 12px 30px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; width: 100%; }
                  button:hover { background-color: #0056b3; }
                  .response { margin-top: 20px; padding: 15px; background-color: #d4edda; border: 1px solid #c3e6cb; border-radius: 4px; color: #155724; }
                  .error { background-color: #f8d7da; border-color: #f5c6cb; color: #721c24; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Submit Your Information</h1>
                  
                  <form id="submitForm">
                      <div class="form-group">
                          <label for="name">Name:</label>
                          <input type="text" id="name" name="name" required placeholder="Enter your name">
                      </div>
                      
                      <div class="form-group">
                          <label for="email">Email:</label>
                          <input type="email" id="email" name="email" required placeholder="Enter your email">
                      </div>
                      
                      <button type="submit">Submit</button>
                  </form>

                  <div id="response" class="response" style="display: none;"></div>
              </div>

              <script>
                  document.getElementById('submitForm').addEventListener('submit', async function(e) {
                      e.preventDefault();
                      
                      const name = document.getElementById('name').value;
                      const email = document.getElementById('email').value;
                      const responseDiv = document.getElementById('response');
                      
                      responseDiv.innerHTML = '<p>Submitting...</p>';
                      responseDiv.style.display = 'block';
                      responseDiv.className = 'response';
                      
                      try {
                          const response = await fetch('/api/', {
                              method: 'POST',
                              headers: {
                                  'Content-Type': 'application/json',
                              },
                              body: JSON.stringify({ name, email })
                          });
                          
                          const result = await response.json();
                          responseDiv.innerHTML = '<h3>✅ Success!</h3><p>' + result.message + '</p>';
                          responseDiv.className = 'response';
                          
                          document.getElementById('name').value = '';
                          document.getElementById('email').value = '';
                          
                      } catch (error) {
                          responseDiv.innerHTML = '<h3>❌ Error:</h3><p>' + error.message + '</p>';
                          responseDiv.className = 'response error';
                      }
                  });
              </script>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copy Nginx configuration file
      copy:
        src: /home/palmu/Terraform-tasks/task2/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload Nginx

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Wait for Nginx to be ready
      wait_for:
        port: 80
        delay: 5
        timeout: 30

    - name: Wait for Nginx on port 3000 to be ready
      wait_for:
        port: 3000
        delay: 5
        timeout: 30

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded